version: "3"

services:
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
    networks:
      - database_network
    restart: on-failure

  db-client:
    container_name: db-client
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    networks:
      - database_network
    restart: on-failure

  postgres-db:
    image: "postgres:12"
    hostname: postgres-db
    container_name: postgres-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - database_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

networks:
  database_network:
    driver: bridge

