version: "3"

services:
  db:
    container_name: postgres-db
    image: "postgres:12"
    restart: on-failure
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - database_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - database_network

networks:
  database_network:
    driver: bridge

